version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ждем, пока PostgreSQL будет готов
    env_file:
      - .env
    environment:
      DB_HOST: db  # Меняем localhost на db ТОЛЬКО ВНУТРИ DOCKER
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: fastapi_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}

volumes:
  pgdata:
