"""Initial tables

Revision ID: 42aabfd7fa19
Revises: 086ef3bbd0d7
Create Date: 2025-02-23 11:20:06.919409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42aabfd7fa19'
down_revision: Union[str, None] = '086ef3bbd0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
